name: myokane
description: Aplikasi Pencatatan Keuangan Pribadi
publish_to: 'none'
version: 7.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  pinput: ^3.0.1
  image_picker: ^1.2.1
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.3.0
  http: ^1.2.1
  package_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true




